///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Dom_ClientSanityTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
	/// <summary>
	/// The class representing the Dom_SanityTestRepository element repository.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.3")]
	[RepositoryFolder("2fb11da8-6c9b-4473-b2e2-32b57231dea5")]
	public partial class Dom_SanityTestRepository : RepoGenBaseFolder
	{
		static Dom_SanityTestRepository instance = new Dom_SanityTestRepository();
		Dom_SanityTestRepositoryFolders.DomNasHomeAppFolder _domnashome;
		Dom_SanityTestRepositoryFolders.ChooseFileToUploadAppFolder _choosefiletoupload;
		Dom_SanityTestRepositoryFolders.NASAppFolder _nas;

		/// <summary>
		/// Gets the singleton class instance representing the Dom_SanityTestRepository element repository.
		/// </summary>
		[RepositoryFolder("2fb11da8-6c9b-4473-b2e2-32b57231dea5")]
		public static Dom_SanityTestRepository Instance
		{
			get { return instance; }
		}

		/// <summary>
		/// Repository class constructor.
		/// </summary>
		public Dom_SanityTestRepository() 
			: base("Dom_SanityTestRepository", "/", null, 0, false, "2fb11da8-6c9b-4473-b2e2-32b57231dea5", ".\\RepositoryImages\\Dom_SanityTestRepository2fb11da8.rximgres")
		{
			_domnashome = new Dom_SanityTestRepositoryFolders.DomNasHomeAppFolder(this);
			_choosefiletoupload = new Dom_SanityTestRepositoryFolders.ChooseFileToUploadAppFolder(this);
			_nas = new Dom_SanityTestRepositoryFolders.NASAppFolder(this);
		}

#region Variables

		string _ViewReqNumLink = "^View\\ Appraisal\\ Request\\ d+";

		/// <summary>
		/// Gets or sets the value of variable ViewReqNumLink.
		/// </summary>
		[TestVariable("87d645c5-b67b-44cb-b99b-3cf9256dfb1a")]
		public string ViewReqNumLink
		{
			get { return _ViewReqNumLink; }
			set { _ViewReqNumLink = value; }
		}

		string _varNasNbr = "";

		/// <summary>
		/// Gets or sets the value of variable varNasNbr.
		/// </summary>
		[TestVariable("736a30a9-f725-43f3-aee1-dd388f2abc03")]
		public string varNasNbr
		{
			get { return _varNasNbr; }
			set { _varNasNbr = value; }
		}

		string _NasNbr = "\\d+";

		/// <summary>
		/// Gets or sets the value of variable NasNbr.
		/// </summary>
		[TestVariable("e3894c25-9671-4650-94f0-98f0613fc8bd")]
		public string NasNbr
		{
			get { return _NasNbr; }
			set { _NasNbr = value; }
		}

		string _searchNbr = "\\d+";

		/// <summary>
		/// Gets or sets the value of variable searchNbr.
		/// </summary>
		[TestVariable("79ae7c5c-abed-47a8-821c-c0c613ca22f6")]
		public string searchNbr
		{
			get { return _searchNbr; }
			set { _searchNbr = value; }
		}

		string _varFromDate = "\\d+";

		/// <summary>
		/// Gets or sets the value of variable varFromDate.
		/// </summary>
		[TestVariable("e7d5faef-042e-4f1a-9d57-f4759c97608d")]
		public string varFromDate
		{
			get { return _varFromDate; }
			set { _varFromDate = value; }
		}

		string _varSearchTbl = "\\trRow\\d+";

		/// <summary>
		/// Gets or sets the value of variable varSearchTbl.
		/// </summary>
		[TestVariable("cc919b80-9500-437b-83dc-bc7e45780b54")]
		public string varSearchTbl
		{
			get { return _varSearchTbl; }
			set { _varSearchTbl = value; }
		}

		string _NewVariable = "trRow\\d5";

		/// <summary>
		/// Gets or sets the value of variable NewVariable.
		/// </summary>
		[TestVariable("47fa4a2c-520e-4440-932e-4ed71b910acc")]
		public string NewVariable
		{
			get { return _NewVariable; }
			set { _NewVariable = value; }
		}

		string _varTRrow = "trRow\\d+";

		/// <summary>
		/// Gets or sets the value of variable varTRrow.
		/// </summary>
		[TestVariable("e1a17729-ddff-4147-8f64-e2adc4d2f39b")]
		public string varTRrow
		{
			get { return _varTRrow; }
			set { _varTRrow = value; }
		}

		string _varTR = "\\d+";

		/// <summary>
		/// Gets or sets the value of variable varTR.
		/// </summary>
		[TestVariable("2fb12b7e-f703-436f-92e8-a60bcc9e8cd7")]
		public string varTR
		{
			get { return _varTR; }
			set { _varTR = value; }
		}

		string _varInd = "1";

		/// <summary>
		/// Gets or sets the value of variable varInd.
		/// </summary>
		[TestVariable("1b491059-d0aa-4eae-b557-de741289a5ac")]
		public string varInd
		{
			get { return _varInd; }
			set { _varInd = value; }
		}

#endregion

		/// <summary>
		/// The Self item info.
		/// </summary>
		[RepositoryItemInfo("2fb11da8-6c9b-4473-b2e2-32b57231dea5")]
		public virtual RepoItemInfo SelfInfo
		{
			get
			{
				return _selfInfo;
			}
		}

		/// <summary>
		/// The DomNasHome folder.
		/// </summary>
		[RepositoryFolder("712e9106-3589-4d9f-a17c-7154eddcbd33")]
		public virtual Dom_SanityTestRepositoryFolders.DomNasHomeAppFolder DomNasHome
		{
			get { return _domnashome; }
		}

		/// <summary>
		/// The ChooseFileToUpload folder.
		/// </summary>
		[RepositoryFolder("e2624051-1e02-48f7-95ea-b0be35d9d8c9")]
		public virtual Dom_SanityTestRepositoryFolders.ChooseFileToUploadAppFolder ChooseFileToUpload
		{
			get { return _choosefiletoupload; }
		}

		/// <summary>
		/// The NAS folder.
		/// </summary>
		[RepositoryFolder("92e56e43-c02e-4215-bdef-eaf77ba9a720")]
		public virtual Dom_SanityTestRepositoryFolders.NASAppFolder NAS
		{
			get { return _nas; }
		}
	}

	/// <summary>
	/// Inner folder classes.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.3")]
	public partial class Dom_SanityTestRepositoryFolders
	{
		/// <summary>
		/// The DomNasHomeAppFolder folder.
		/// </summary>
		[RepositoryFolder("712e9106-3589-4d9f-a17c-7154eddcbd33")]
		public partial class DomNasHomeAppFolder : RepoGenBaseFolder
		{
			Dom_SanityTestRepositoryFolders.RequestTableFolder _requesttable;
			Dom_SanityTestRepositoryFolders.MenuDisplayFolder _menudisplay;
			RepoItemInfo _useridInfo;
			RepoItemInfo _passwordInfo;
			RepoItemInfo _submitInfo;
			RepoItemInfo _logoutInfo;
			RepoItemInfo _requestserviceInfo;
			RepoItemInfo _searchfilterInfo;
			RepoItemInfo _rememberusernameInfo;

			/// <summary>
			/// Creates a new DomNasHome  folder.
			/// </summary>
			public DomNasHomeAppFolder(RepoGenBaseFolder parentFolder) :
					base("DomNasHome", "/dom[@domain='test.nationwideappraisals.com']", parentFolder, 30000, null, false, "712e9106-3589-4d9f-a17c-7154eddcbd33", "")
			{
				_requesttable = new Dom_SanityTestRepositoryFolders.RequestTableFolder(this);
				_menudisplay = new Dom_SanityTestRepositoryFolders.MenuDisplayFolder(this);
				_useridInfo = new RepoItemInfo(this, "Userid", ".//input[#'userid']", 30000, null, "ef41ee37-8098-4634-b722-6604d5b04f9c");
				_passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "3532f3eb-fd3e-45a7-83df-a7c8d92db0f9");
				_submitInfo = new RepoItemInfo(this, "Submit", ".//div[#'main']/div[1]//div[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']/div[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']//form[@name='loginform']/div[4]/input[@type='submit']", 30000, null, "db2cb966-e369-4714-bcc1-219472f951cd");
				_logoutInfo = new RepoItemInfo(this, "LogOut", ".//frame[#'topFrame']//a[@innertext='Log out']", 30000, null, "66e55b58-01fa-43ec-8275-f7d87915b70d");
				_requestserviceInfo = new RepoItemInfo(this, "RequestService", ".//frameset[#'mainFrameset']/frame[@name='menu_bar']//div[#'menucontainer']/table//a[@innertext='Request Service']", 30000, null, "d8859232-84c3-4420-bc91-0bd1e9da2a0b");
				_searchfilterInfo = new RepoItemInfo(this, "SearchFilter", ".//frameset[#'mainFrameset']/frame[@name='menu_bar']//div[#'menucontainer']/table//a[@innertext='Search Filter']", 30000, null, "e1cd054d-1ed6-4800-bcf8-6720250f9808");
				_rememberusernameInfo = new RepoItemInfo(this, "RememberUserName", ".//input[#'rememberUserName']", 30000, null, "d943458d-9311-409e-8510-f90b0119b95c");
			}

			/// <summary>
			/// The Self item.
			/// </summary>
			[RepositoryItem("712e9106-3589-4d9f-a17c-7154eddcbd33")]
			public virtual Ranorex.WebDocument Self
			{
				get
				{
					return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
				}
			}

			/// <summary>
			/// The Self item info.
			/// </summary>
			[RepositoryItemInfo("712e9106-3589-4d9f-a17c-7154eddcbd33")]
			public virtual RepoItemInfo SelfInfo
			{
				get
				{
					return _selfInfo;
				}
			}

			/// <summary>
			/// The Userid item.
			/// </summary>
			[RepositoryItem("ef41ee37-8098-4634-b722-6604d5b04f9c")]
			public virtual Ranorex.InputTag Userid
			{
				get
				{
					return _useridInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The Userid item info.
			/// </summary>
			[RepositoryItemInfo("ef41ee37-8098-4634-b722-6604d5b04f9c")]
			public virtual RepoItemInfo UseridInfo
			{
				get
				{
					return _useridInfo;
				}
			}

			/// <summary>
			/// The Password item.
			/// </summary>
			[RepositoryItem("3532f3eb-fd3e-45a7-83df-a7c8d92db0f9")]
			public virtual Ranorex.InputTag Password
			{
				get
				{
					return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The Password item info.
			/// </summary>
			[RepositoryItemInfo("3532f3eb-fd3e-45a7-83df-a7c8d92db0f9")]
			public virtual RepoItemInfo PasswordInfo
			{
				get
				{
					return _passwordInfo;
				}
			}

			/// <summary>
			/// The Submit item.
			/// </summary>
			[RepositoryItem("db2cb966-e369-4714-bcc1-219472f951cd")]
			public virtual Ranorex.InputTag Submit
			{
				get
				{
					return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The Submit item info.
			/// </summary>
			[RepositoryItemInfo("db2cb966-e369-4714-bcc1-219472f951cd")]
			public virtual RepoItemInfo SubmitInfo
			{
				get
				{
					return _submitInfo;
				}
			}

			/// <summary>
			/// The LogOut item.
			/// </summary>
			[RepositoryItem("66e55b58-01fa-43ec-8275-f7d87915b70d")]
			public virtual Ranorex.ATag LogOut
			{
				get
				{
					return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
				}
			}

			/// <summary>
			/// The LogOut item info.
			/// </summary>
			[RepositoryItemInfo("66e55b58-01fa-43ec-8275-f7d87915b70d")]
			public virtual RepoItemInfo LogOutInfo
			{
				get
				{
					return _logoutInfo;
				}
			}

			/// <summary>
			/// The RequestService item.
			/// </summary>
			[RepositoryItem("d8859232-84c3-4420-bc91-0bd1e9da2a0b")]
			public virtual Ranorex.ATag RequestService
			{
				get
				{
					return _requestserviceInfo.CreateAdapter<Ranorex.ATag>(true);
				}
			}

			/// <summary>
			/// The RequestService item info.
			/// </summary>
			[RepositoryItemInfo("d8859232-84c3-4420-bc91-0bd1e9da2a0b")]
			public virtual RepoItemInfo RequestServiceInfo
			{
				get
				{
					return _requestserviceInfo;
				}
			}

			/// <summary>
			/// The SearchFilter item.
			/// </summary>
			[RepositoryItem("e1cd054d-1ed6-4800-bcf8-6720250f9808")]
			public virtual Ranorex.ATag SearchFilter
			{
				get
				{
					return _searchfilterInfo.CreateAdapter<Ranorex.ATag>(true);
				}
			}

			/// <summary>
			/// The SearchFilter item info.
			/// </summary>
			[RepositoryItemInfo("e1cd054d-1ed6-4800-bcf8-6720250f9808")]
			public virtual RepoItemInfo SearchFilterInfo
			{
				get
				{
					return _searchfilterInfo;
				}
			}

			/// <summary>
			/// The RememberUserName item.
			/// </summary>
			[RepositoryItem("d943458d-9311-409e-8510-f90b0119b95c")]
			public virtual Ranorex.InputTag RememberUserName
			{
				get
				{
					return _rememberusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The RememberUserName item info.
			/// </summary>
			[RepositoryItemInfo("d943458d-9311-409e-8510-f90b0119b95c")]
			public virtual RepoItemInfo RememberUserNameInfo
			{
				get
				{
					return _rememberusernameInfo;
				}
			}

			/// <summary>
			/// The RequestTable folder.
			/// </summary>
			[RepositoryFolder("e93d5c95-fbb8-4a6f-951a-a9409bac3bc2")]
			public virtual Dom_SanityTestRepositoryFolders.RequestTableFolder RequestTable
			{
				get { return _requesttable; }
			}

			/// <summary>
			/// The MenuDisplay folder.
			/// </summary>
			[RepositoryFolder("71edc462-14fe-414c-a1f0-4feb505528ff")]
			public virtual Dom_SanityTestRepositoryFolders.MenuDisplayFolder MenuDisplay
			{
				get { return _menudisplay; }
			}
		}

		/// <summary>
		/// The RequestTableFolder folder.
		/// </summary>
		[RepositoryFolder("e93d5c95-fbb8-4a6f-951a-a9409bac3bc2")]
		public partial class RequestTableFolder : RepoGenBaseFolder
		{
			RepoItemInfo _appcityInfo;
			RepoItemInfo _apppostalcodeInfo;
			RepoItemInfo _appstreetnumInfo;
			RepoItemInfo _appstreetnameInfo;
			RepoItemInfo _appstreettypeInfo;
			RepoItemInfo _appstreetdirInfo;

			/// <summary>
			/// Creates a new RequestTable  folder.
			/// </summary>
			public RequestTableFolder(RepoGenBaseFolder parentFolder) :
					base("RequestTable", ".//frameset[#'mainFrameset']/frame[@name='menu_display']//form[@name='appreqform']/table", parentFolder, 30000, null, false, "e93d5c95-fbb8-4a6f-951a-a9409bac3bc2", "")
			{
				_appcityInfo = new RepoItemInfo(this, "AppCity", ".//input[@name='app_city']", 30000, null, "404c5b00-67d0-4bb6-ad33-e6a329a45c18");
				_apppostalcodeInfo = new RepoItemInfo(this, "AppPostalCode", ".//input[@name='app_postal_code']", 30000, null, "9365a913-c1f8-491b-aae6-0e397241e2bf");
				_appstreetnumInfo = new RepoItemInfo(this, "AppStreetNum", ".//input[@name='app_street_num']", 30000, null, "d5022093-24a6-405b-9d25-ad81c8b1eef9");
				_appstreetnameInfo = new RepoItemInfo(this, "AppStreetName", ".//input[@name='app_street_name']", 30000, null, "ece8c35b-7d67-417c-8578-c8079a60c374");
				_appstreettypeInfo = new RepoItemInfo(this, "AppStreetType", ".//input[@name='app_street_type']", 30000, null, "fd210230-ef5b-4222-b66c-bf1ebae16eb9");
				_appstreetdirInfo = new RepoItemInfo(this, "AppStreetDir", ".//select[@name='app_street_dir']", 30000, null, "be0d38a0-9758-4472-8596-ea18ded0e0a8");
			}

			/// <summary>
			/// The Self item.
			/// </summary>
			[RepositoryItem("e93d5c95-fbb8-4a6f-951a-a9409bac3bc2")]
			public virtual Ranorex.Table Self
			{
				get
				{
					return _selfInfo.CreateAdapter<Ranorex.Table>(true);
				}
			}

			/// <summary>
			/// The Self item info.
			/// </summary>
			[RepositoryItemInfo("e93d5c95-fbb8-4a6f-951a-a9409bac3bc2")]
			public virtual RepoItemInfo SelfInfo
			{
				get
				{
					return _selfInfo;
				}
			}

			/// <summary>
			/// The AppCity item.
			/// </summary>
			[RepositoryItem("404c5b00-67d0-4bb6-ad33-e6a329a45c18")]
			public virtual Ranorex.InputTag AppCity
			{
				get
				{
					return _appcityInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The AppCity item info.
			/// </summary>
			[RepositoryItemInfo("404c5b00-67d0-4bb6-ad33-e6a329a45c18")]
			public virtual RepoItemInfo AppCityInfo
			{
				get
				{
					return _appcityInfo;
				}
			}

			/// <summary>
			/// The AppPostalCode item.
			/// </summary>
			[RepositoryItem("9365a913-c1f8-491b-aae6-0e397241e2bf")]
			public virtual Ranorex.InputTag AppPostalCode
			{
				get
				{
					return _apppostalcodeInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The AppPostalCode item info.
			/// </summary>
			[RepositoryItemInfo("9365a913-c1f8-491b-aae6-0e397241e2bf")]
			public virtual RepoItemInfo AppPostalCodeInfo
			{
				get
				{
					return _apppostalcodeInfo;
				}
			}

			/// <summary>
			/// The AppStreetNum item.
			/// </summary>
			[RepositoryItem("d5022093-24a6-405b-9d25-ad81c8b1eef9")]
			public virtual Ranorex.InputTag AppStreetNum
			{
				get
				{
					return _appstreetnumInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The AppStreetNum item info.
			/// </summary>
			[RepositoryItemInfo("d5022093-24a6-405b-9d25-ad81c8b1eef9")]
			public virtual RepoItemInfo AppStreetNumInfo
			{
				get
				{
					return _appstreetnumInfo;
				}
			}

			/// <summary>
			/// The AppStreetName item.
			/// </summary>
			[RepositoryItem("ece8c35b-7d67-417c-8578-c8079a60c374")]
			public virtual Ranorex.InputTag AppStreetName
			{
				get
				{
					return _appstreetnameInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The AppStreetName item info.
			/// </summary>
			[RepositoryItemInfo("ece8c35b-7d67-417c-8578-c8079a60c374")]
			public virtual RepoItemInfo AppStreetNameInfo
			{
				get
				{
					return _appstreetnameInfo;
				}
			}

			/// <summary>
			/// The AppStreetType item.
			/// </summary>
			[RepositoryItem("fd210230-ef5b-4222-b66c-bf1ebae16eb9")]
			public virtual Ranorex.InputTag AppStreetType
			{
				get
				{
					return _appstreettypeInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The AppStreetType item info.
			/// </summary>
			[RepositoryItemInfo("fd210230-ef5b-4222-b66c-bf1ebae16eb9")]
			public virtual RepoItemInfo AppStreetTypeInfo
			{
				get
				{
					return _appstreettypeInfo;
				}
			}

			/// <summary>
			/// The AppStreetDir item.
			/// </summary>
			[RepositoryItem("be0d38a0-9758-4472-8596-ea18ded0e0a8")]
			public virtual Ranorex.SelectTag AppStreetDir
			{
				get
				{
					return _appstreetdirInfo.CreateAdapter<Ranorex.SelectTag>(true);
				}
			}

			/// <summary>
			/// The AppStreetDir item info.
			/// </summary>
			[RepositoryItemInfo("be0d38a0-9758-4472-8596-ea18ded0e0a8")]
			public virtual RepoItemInfo AppStreetDirInfo
			{
				get
				{
					return _appstreetdirInfo;
				}
			}
		}

		/// <summary>
		/// The MenuDisplayFolder folder.
		/// </summary>
		[RepositoryFolder("71edc462-14fe-414c-a1f0-4feb505528ff")]
		public partial class MenuDisplayFolder : RepoGenBaseFolder
		{
			RepoItemInfo _unitnumInfo;
			RepoItemInfo _servicetypeoptionInfo;
			RepoItemInfo _submitbtnInfo;
			RepoItemInfo _servicetypedrivebyInfo;
			RepoItemInfo _purchaseInfo;
			RepoItemInfo _refinanceInfo;
			RepoItemInfo _priceInfo;
			RepoItemInfo _mortgageamtInfo;
			RepoItemInfo _apprefnbrInfo;
			RepoItemInfo _appbranbrInfo;
			RepoItemInfo _appnameInfo;
			RepoItemInfo _appcontactnameInfo;
			RepoItemInfo _tel1Info;
			RepoItemInfo _tel2Info;
			RepoItemInfo _tel3Info;
			RepoItemInfo _bustel1Info;
			RepoItemInfo _bustel2Info;
			RepoItemInfo _bustel3Info;
			RepoItemInfo _bustelextInfo;
			RepoItemInfo _spdirectionInfo;
			RepoItemInfo _invoiceInfo;
			RepoItemInfo _applicantpayInfo;
			RepoItemInfo _selectappraisersubmitbtnInfo;
			RepoItemInfo _uploadsupportingdocumentshereInfo;
			RepoItemInfo _yourrequesthasbeensubmittedInfo;
			RepoItemInfo _nasreqnumInfo;
			RepoItemInfo _clientrefnumInfo;
			RepoItemInfo _statusoptInfo;
			RepoItemInfo _createdatefromInfo;
			RepoItemInfo _createdatetoInfo;
			RepoItemInfo _searchsubmitInfo;
			RepoItemInfo _nasnumtdtagInfo;
			RepoItemInfo _commentonrequestInfo;
			RepoItemInfo _sendcommenttoappraiserfromclientInfo;
			RepoItemInfo _logclientcommentInfo;
			RepoItemInfo _commenttextInfo;
			RepoItemInfo _submitcommentInfo;
			RepoItemInfo _commentsweresuccessfullysubmittedInfo;
			RepoItemInfo _commentpostedInfo;
			RepoItemInfo _strongtag1recordsfoundInfo;
			RepoItemInfo _ptagInfo;
			RepoItemInfo _labeltagnasnumInfo;
			RepoItemInfo _viewrequestbtnInfo;
			RepoItemInfo _uploadsupportdocubtnInfo;
			RepoItemInfo _appraisalhistorybtnInfo;
			RepoItemInfo _cancelledbtnInfo;
			RepoItemInfo _underreviewbtnInfo;
			RepoItemInfo _reviewbtnInfo;
			RepoItemInfo _appraisalrequesthistoryreportInfo;
			RepoItemInfo _appraisalrequestnumberInfo;
			RepoItemInfo _regiontypeInfo;
			RepoItemInfo _tdtagstatusInfo;
			RepoItemInfo _tdtagapppriceInfo;
			RepoItemInfo _tdtagapppricetaxInfo;
			RepoItemInfo _tdtagtimestampInfo;
			RepoItemInfo _appraisalserviceinfoInfo;
			RepoItemInfo _addressinfoInfo;
			RepoItemInfo _postalcodeinfoInfo;
			RepoItemInfo _priceinformationInfo;
			RepoItemInfo _mortgageinformationInfo;
			RepoItemInfo _clientrefnbrinfoInfo;
			RepoItemInfo _datecreatedinfoInfo;
			RepoItemInfo _statusinfoInfo;
			RepoItemInfo _nasrequestnumberInfo;
			RepoItemInfo _strongtagviewappraisalnumInfo;
			RepoItemInfo _strongtagyourappraisalhasbeensenInfo;
			RepoItemInfo _tablesearchresultInfo;
			RepoItemInfo _labeltagnasnumberfoundInfo;
			RepoItemInfo _browsefiletouploadInfo;
			RepoItemInfo _uploadsubmitInfo;
			RepoItemInfo _supportingdocumentpdfInfo;
			RepoItemInfo _supportingdocumentshavebeenuploadedInfo;
			RepoItemInfo _buttontagyesInfo;
			RepoItemInfo _buttontagnoInfo;
			RepoItemInfo _statuschangedfromnewtocancelledforInfo;
			RepoItemInfo _strongtagstatusInfo;
			RepoItemInfo _viewuserreqInfo;
			RepoItemInfo _activereqsample1Info;

			/// <summary>
			/// Creates a new MenuDisplay  folder.
			/// </summary>
			public MenuDisplayFolder(RepoGenBaseFolder parentFolder) :
					base("MenuDisplay", ".//frameset[#'mainFrameset']/frame[@name='menu_display']", parentFolder, 30000, null, false, "71edc462-14fe-414c-a1f0-4feb505528ff", "")
			{
				_unitnumInfo = new RepoItemInfo(this, "UnitNum", ".//input[#'oTarget']", 30000, null, "51955b5b-bba0-4340-9885-e01a80c9c422");
				_servicetypeoptionInfo = new RepoItemInfo(this, "ServiceTypeOption", ".//input[@id='service_type']", 30000, null, "18a51a00-7bf3-46b4-92d6-776b4181f410");
				_submitbtnInfo = new RepoItemInfo(this, "SubmitBtn", ".//input[#'submitBtn']", 30000, null, "85b74e3a-02ec-461b-b365-c88cf0a716e8");
				_servicetypedrivebyInfo = new RepoItemInfo(this, "ServiceTypeDriveBy", ".//div[#'serviceTypeDiv']//input[@name='service_type' and @type='radio' and @value='Drive-By']", 30000, null, "31fbec24-d1c4-4c9f-9e53-c76a543de788");
				_purchaseInfo = new RepoItemInfo(this, "Purchase", ".//tr[#'loanTypeRow']/?/?/table//input[@name='R2']", 30000, null, "f69c1733-71d2-49d3-91a9-3a843293cc63");
				_refinanceInfo = new RepoItemInfo(this, "Refinance", ".//tr[#'loanTypeRow']/?/?/table//input[@type='radio' and @value='Refinance Amount']", 30000, null, "7294c637-b0ab-4bbf-946f-de40a2c34a8c");
				_priceInfo = new RepoItemInfo(this, "Price", ".//td[#'loanValue']/input[@name='price']", 30000, null, "4da22560-7333-48cd-b5c0-2d5e7ff8205b");
				_mortgageamtInfo = new RepoItemInfo(this, "MortgageAmt", ".//td[#'mortgageAmt']/input[@name='mortgage_amt']", 30000, null, "e1ee5977-9dcb-4cb9-b5a1-81ca3e392d47");
				_apprefnbrInfo = new RepoItemInfo(this, "AppRefNbr", ".//input[#'app_ref_nbr']", 30000, null, "5f688764-09d5-48bd-a380-ae3342c47239");
				_appbranbrInfo = new RepoItemInfo(this, "AppBraNbr", ".//input[#'app_bra_nbr']", 30000, null, "19a61ca8-49ea-43af-b226-22e814fb6bee");
				_appnameInfo = new RepoItemInfo(this, "AppName", ".//td[#'appnameGeneral']/input[@name='app_name']", 30000, null, "beac09b5-cae9-4655-bd6c-69edccdc2583");
				_appcontactnameInfo = new RepoItemInfo(this, "AppContactName", ".//td[#'conname']/input[@name='app_contact_name']", 30000, null, "75cfc4f9-d0d8-4b65-b218-0631cf7ddf23");
				_tel1Info = new RepoItemInfo(this, "Tel1", ".//input[#'tel1']", 30000, null, "cf077aa8-4f68-46ec-94ac-214a4d1953e4");
				_tel2Info = new RepoItemInfo(this, "Tel2", ".//input[#'tel2']", 30000, null, "b9cdd3a9-5b1d-4b06-9236-8f126dd0944b");
				_tel3Info = new RepoItemInfo(this, "Tel3", ".//input[#'tel3']", 30000, null, "21d0436e-6988-445f-b303-ebdd4fe2b9e3");
				_bustel1Info = new RepoItemInfo(this, "BusTel1", ".//input[#'tel4']", 30000, null, "92e518e2-9d5a-4577-bb03-de46cd8ab281");
				_bustel2Info = new RepoItemInfo(this, "BusTel2", ".//input[#'tel5']", 30000, null, "8f9340f1-f39e-4f65-8192-73454505e972");
				_bustel3Info = new RepoItemInfo(this, "BusTel3", ".//input[#'tel6']", 30000, null, "9fe59ab4-c3f5-4b28-b567-e53769b71f11");
				_bustelextInfo = new RepoItemInfo(this, "BusTelExt", ".//input[#'tel7']", 30000, null, "d1303777-6ad4-41fc-a5e9-38941c711ed1");
				_spdirectionInfo = new RepoItemInfo(this, "SpDirection", ".//div[#'specDirTable']//textarea[@wrap='soft']", 30000, null, "29afea55-820f-4b8e-902d-f2ef56912360");
				_invoiceInfo = new RepoItemInfo(this, "Invoice", ".//input[#'inv']", 30000, null, "a8121a17-e9ac-4b17-a00c-22cc72dd37e5");
				_applicantpayInfo = new RepoItemInfo(this, "ApplicantPay", ".//tr[#'payCOD']/?/?/input[@id='cod']", 30000, null, "a7ab662b-3c00-4e67-8d82-a9106c1b5173");
				_selectappraisersubmitbtnInfo = new RepoItemInfo(this, "SelectAppraiserSubmitBtn", "?/?/form[@name='f_form']/?/?/input[@name='B1']", 30000, null, "4dcc9332-858d-4496-bc96-0a92327cc3fd");
				_uploadsupportingdocumentshereInfo = new RepoItemInfo(this, "UploadSupportingDocumentsHere", ".//strong[@innertext~'^Upload\\ supporting\\ documen']", 30000, null, "a893ef6a-0f00-4754-9555-5dd906532bc9");
				_yourrequesthasbeensubmittedInfo = new RepoItemInfo(this, "YourRequestHasBeenSubmitted", "?/?/h1[@innertext~'^Your\\ request\\ has\\ been\\ sub']", 30000, null, "b8cea039-73a9-4cc8-be38-3208a4fa9110");
				_nasreqnumInfo = new RepoItemInfo(this, "NasReqNum", ".//input[#'nas_req_num']", 30000, null, "ee7fbbb8-d254-457d-a441-b1145ac14d35");
				_clientrefnumInfo = new RepoItemInfo(this, "ClientRefNum", ".//input[#'client_ref_num']", 30000, null, "e4fc351b-0311-489f-b449-ecfff5e7e1aa");
				_statusoptInfo = new RepoItemInfo(this, "StatusOpt", ".//select[#'status_opt']", 30000, null, "12912f1a-8398-4f3a-b64d-9201282a2532");
				_createdatefromInfo = new RepoItemInfo(this, "CreateDateFrom", ".//input[@id='create_date_from' and @name='create_date_from' and @tagvalue~'']", 30000, null, "72877c97-88e0-41e8-961e-15f41aea6275");
				_createdatetoInfo = new RepoItemInfo(this, "CreateDateTo", ".//input[@id='create_date_to' and @class='inputField' and @tagvalue~'' and @tagname='input']", 30000, null, "2bb38741-01c8-474f-9a25-f518bf41e263");
				_searchsubmitInfo = new RepoItemInfo(this, "SearchSubmit", "?/?/form[@name='appfilter']/?/?/input[@type='submit']", 30000, null, "f78d9d66-c4f4-404d-b758-d4f284d92763");
				_nasnumtdtagInfo = new RepoItemInfo(this, "NasNumTdTag", ".//tr[#'trRow1']/td[2]", 30000, null, "39c54391-0502-4aea-ac8a-9f3f5a519043");
				_commentonrequestInfo = new RepoItemInfo(this, "CommentOnRequest", ".//div[#'subContainer']/table[2]//input[@value='Comment On Request']", 30000, null, "77ef77d2-cfe8-4958-9676-7925cdf8bc68");
				_sendcommenttoappraiserfromclientInfo = new RepoItemInfo(this, "SendCommentToAppraiserFromClient", ".//input[#'sendCommentToAppraiserFromClient']", 30000, null, "8d34924f-d6f1-44dc-a132-7a862ab54e21");
				_logclientcommentInfo = new RepoItemInfo(this, "LogClientComment", ".//input[#'logClientComment']", 30000, null, "19e0d101-7294-4e4c-8ea7-6e4cd5c08b6e");
				_commenttextInfo = new RepoItemInfo(this, "CommentText", ".//textarea[#'commentText']", 30000, null, "25f55063-6aab-4d73-abe5-8255e5814b63");
				_submitcommentInfo = new RepoItemInfo(this, "SubmitComment", ".//input[#'submitForm']", 30000, null, "606dbd8a-e84c-4969-acd6-f88df46c188a");
				_commentsweresuccessfullysubmittedInfo = new RepoItemInfo(this, "CommentsWereSuccessfullySubmitted", ".//form[#'commentForm']/?/?/div[@innertext~'^Comments\\ were\\ successfull']", 30000, null, "4951f5a7-5126-49bf-a181-e8fe591ba254");
				_commentpostedInfo = new RepoItemInfo(this, "CommentPosted", ".//form[#'commentForm']//table//tr[2]//td[3]", 30000, null, "1bd80c6e-cc05-4fb6-ab9b-17ee4aed5dd3");
				_strongtag1recordsfoundInfo = new RepoItemInfo(this, "StrongTag1RecordSFound", ".//form[@name='f_form']/?/?/strong[@innertext~'^\\ \\ \\ \\ 1\\ record\\(s\\)\\ found']", 30000, null, "bb6e775b-900e-4c83-b74f-deaba08c4e87");
				_ptagInfo = new RepoItemInfo(this, "PTag", ".//form[@name='f_form']/p[@innertext='  ']", 30000, null, "8e609488-2adf-4979-8cc8-08ad41bb5cc7");
				_labeltagnasnumInfo = new RepoItemInfo(this, "LabelTagNasNum", ".//tr[#'trRow1']//td[2]//label[1]", 30000, null, "473d2378-3b1c-4b51-8bf0-f64512d2137a");
				_viewrequestbtnInfo = new RepoItemInfo(this, "ViewRequestBtn", ".//div[#'subContainer']/table[2]//input[@type='button']", 30000, null, "49948270-ff00-4134-9980-6bbf0b53f848");
				_uploadsupportdocubtnInfo = new RepoItemInfo(this, "UploadSupportDocuBtn", ".//div[#'subContainer']/table[2]//input[@value~'^Upload\\ Supporting\\ Documen']", 30000, null, "45ebc6e4-64e0-4279-8573-bc0c39366763");
				_appraisalhistorybtnInfo = new RepoItemInfo(this, "AppraisalHistoryBtn", ".//div[#'subContainer']/table[2]//input[@value='Appraisal History']", 30000, null, "a4416a86-e89a-4ddd-aef8-045b79fc9732");
				_cancelledbtnInfo = new RepoItemInfo(this, "CancelledBtn", ".//table[#'tblChangeStatus']//input[@type='button']", 30000, null, "a7fcb4fe-ede3-4a71-b732-eb76134f0458");
				_underreviewbtnInfo = new RepoItemInfo(this, "UnderReviewBtn", ".//table[#'tblChangeStatus']//input[@value='Under Review']", 30000, null, "c7446e24-ae90-4759-917e-2e0989e10036");
				_reviewbtnInfo = new RepoItemInfo(this, "ReviewBtn", ".//table[#'tblChangeStatus']//input[@value='Reviewed']", 30000, null, "eca9eb6e-7f49-4153-979d-978c92194755");
				_appraisalrequesthistoryreportInfo = new RepoItemInfo(this, "AppraisalRequestHistoryReport", "?/?/h1[@innertext~'^Appraisal\\ Request\\ History']", 30000, null, "f917aecb-ebbf-454d-b177-caed778f1d14");
				_appraisalrequestnumberInfo = new RepoItemInfo(this, "AppraisalRequestNumber", ".//h2[@innertext~'^Appraisal\\ Request\\ Number:']", 30000, null, "03a98407-4a29-487e-bbb4-33ed11c68955");
				_regiontypeInfo = new RepoItemInfo(this, "RegionType", "body[@innertext='    ']/?/?/h2[@innertext~'Region Type: *']", 30000, null, "acc764df-6bd0-4105-a72d-ba71b7f2fd82");
				_tdtagstatusInfo = new RepoItemInfo(this, "TdTagStatus", ".//table[@innertext=' ']//td[2]//td[2]", 30000, null, "827865c5-71fd-41b6-92e0-21d831e5daba");
				_tdtagapppriceInfo = new RepoItemInfo(this, "TdTagAppPrice", ".//table[@innertext=' ']/tbody/tr[2]/td[4]", 30000, null, "3a730fa9-b11c-4395-8634-c770e52eb082");
				_tdtagapppricetaxInfo = new RepoItemInfo(this, "TdTagAppPriceTax", ".//table[@innertext=' ']/tbody/tr[2]/td[5]", 30000, null, "5c8faddf-d749-4b0d-b7da-5b5240358733");
				_tdtagtimestampInfo = new RepoItemInfo(this, "TdTagTimeStamp", ".//table[@innertext=' ']//tr[2]//td[1]", 30000, null, "3a7f872d-4b02-478f-9622-5f1c7e558b86");
				_appraisalserviceinfoInfo = new RepoItemInfo(this, "AppraisalServiceInfo", "body[@innertext~'^\\ \\ ']/table[2]/tbody/tr[1]/td[1]/table[@innertext='']/tbody/tr[3]/td[2]", 30000, null, "8e586b38-3c70-4c3f-84f7-9164d4389d8f");
				_addressinfoInfo = new RepoItemInfo(this, "AddressInfo", "body[@innertext~'^\\ \\ ']/table[2]/tbody/tr[1]/td[2]/table[@innertext='']//tr[2]//td[2]", 30000, null, "a7b240dc-0248-4536-b1f1-dd7f78e17e1c");
				_postalcodeinfoInfo = new RepoItemInfo(this, "PostalCodeInfo", "body/table[2]/tbody/tr[1]/td[2]/table[@innertext='']/tbody/tr[6]/td[2]", 30000, null, "e02c17cb-2cbf-412f-9a5c-8588a5094e9c");
				_priceinformationInfo = new RepoItemInfo(this, "Priceinformation", "body/table[2]/tbody/tr[3]/td[1]/table[1]/tbody/tr[2]/td[2]", 30000, null, "d5b9980a-647f-4f64-9616-793bd25a36ee");
				_mortgageinformationInfo = new RepoItemInfo(this, "MortgageInformation", "body/table[2]/tbody/tr[3]/td[1]/table[1]/tbody/tr[5]/td[2]", 30000, null, "efb81b76-b4f4-4fdd-aff1-2a6f6c775b22");
				_clientrefnbrinfoInfo = new RepoItemInfo(this, "ClientRefNbrInfo", "body/table[2]/tbody/tr[3]/td[1]/table[2]/tbody/tr[4]/td[2]", 30000, null, "99df1708-2dcd-4440-9e3c-33b136608077");
				_datecreatedinfoInfo = new RepoItemInfo(this, "DateCreatedInfo", "body/table[2]/tbody/tr[3]/td[1]/table[2]/tbody/tr[3]/td[2]", 30000, null, "c0101e01-6b55-4d6a-836c-bcb15f23002a");
				_statusinfoInfo = new RepoItemInfo(this, "StatusInfo", "body/table[2]/tbody/tr[3]/td[1]/table[2]/tbody/tr[2]/td[2]", 30000, null, "0efac6c3-6591-484e-aa27-d577cbcbbf75");
				_nasrequestnumberInfo = new RepoItemInfo(this, "NASRequestNumber", "?/?/div[@innertext~'^NAS\\ Request\\ Number:']", 30000, null, "acf9b1c0-a4b0-4300-a2d4-f74cc1978f21");
				_strongtagviewappraisalnumInfo = new RepoItemInfo(this, "StrongTagViewAppraisalNum", ".//strong[@innertext~'^\\ \\ \\ \\ \\ \\ View\\ Ap']", 30000, null, "ea9f917f-7a3d-4cbf-9868-c09c2bdd5001");
				_strongtagyourappraisalhasbeensenInfo = new RepoItemInfo(this, "StrongTagYourAppraisalHasBeenSen", ".//strong[@innertext~'^Your\\ Appraisal\\ has\\ be']", 30000, null, "66b8b0b7-383d-4aff-8bdd-e9814020e28a");
				_tablesearchresultInfo = new RepoItemInfo(this, "TableSearchResult", ".//div[#'subContainer']/table[@innertext='     ']", 30000, null, "f028d486-98b9-4403-8e72-c18457bc3dd7");
				_labeltagnasnumberfoundInfo = new RepoItemInfo(this, "LabelTagNasNumberFound", ".//tr[#'trRow5']//td[2]//label[]", 30000, null, "f560aa96-34d0-4d20-bdfb-23bb52309771");
				_browsefiletouploadInfo = new RepoItemInfo(this, "BrowseFileToUpload", ".//form[#'form1']/table[@innertext='   ']/tbody/tr[3]/?/?/input[@id='file' and @accept=null()]", 30000, null, "498d4528-a437-452d-8038-09b8b6448847");
				_uploadsubmitInfo = new RepoItemInfo(this, "UploadSubmit", ".//form[#'form1']/input[@name='Submit']", 30000, null, "0f5f6478-c883-417e-8d30-d3ad7f2adb16");
				_supportingdocumentpdfInfo = new RepoItemInfo(this, "SupportingDocumentPdf", "?/?/div[@innertext~'^\\ ']/table[5]//a[@innertext='Supporting Document(.pdf)']", 30000, null, "20e9fe3b-437c-4c12-ab15-f5dc9baad096");
				_supportingdocumentshavebeenuploadedInfo = new RepoItemInfo(this, "SupportingDocumentsHaveBeenUploaded", "?/?/h2[@innertext~'^Supporting\\ Documents\\ have']", 30000, null, "c1d6beb4-eb94-4019-b8c1-20d434d02061");
				_buttontagyesInfo = new RepoItemInfo(this, "ButtonTagYes", ".//button[@innertext='Yes']", 30000, null, "392551e9-756b-4da6-a9dd-227fbc166e2e");
				_buttontagnoInfo = new RepoItemInfo(this, "ButtonTagNo", ".//button[@innertext='No']", 30000, null, "61f21a2f-0bb3-45ac-99f3-04fcae994b1c");
				_statuschangedfromnewtocancelledforInfo = new RepoItemInfo(this, "StatusChangedFromNewToCancelledFor", ".//p[@innertext~'^Status\\ changed\\ from\\ New\\ t']", 30000, null, "17518023-b08b-4b19-ab1e-085fa0a42627");
				_strongtagstatusInfo = new RepoItemInfo(this, "StrongTagStatus", ".//tr[2]//td[7]/strong[]", 30000, null, "22dffa42-456b-477d-90df-300b73e97d8b");
				_viewuserreqInfo = new RepoItemInfo(this, "ViewUserReq", ".//input[#'view_user_req']", 30000, null, "9341209e-f52c-42cc-aca2-8e1069f18428");
				_activereqsample1Info = new RepoItemInfo(this, "ActiveReqSample1", ".//table[@tagname='table' and @id='sample_1']", 30000, null, "24d37fc6-40dc-4a5a-a39a-b6575aa9f5ba");
			}

			/// <summary>
			/// The Self item.
			/// </summary>
			[RepositoryItem("71edc462-14fe-414c-a1f0-4feb505528ff")]
			public virtual Ranorex.FrameTag Self
			{
				get
				{
					return _selfInfo.CreateAdapter<Ranorex.FrameTag>(true);
				}
			}

			/// <summary>
			/// The Self item info.
			/// </summary>
			[RepositoryItemInfo("71edc462-14fe-414c-a1f0-4feb505528ff")]
			public virtual RepoItemInfo SelfInfo
			{
				get
				{
					return _selfInfo;
				}
			}

			/// <summary>
			/// The UnitNum item.
			/// </summary>
			[RepositoryItem("51955b5b-bba0-4340-9885-e01a80c9c422")]
			public virtual Ranorex.InputTag UnitNum
			{
				get
				{
					return _unitnumInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The UnitNum item info.
			/// </summary>
			[RepositoryItemInfo("51955b5b-bba0-4340-9885-e01a80c9c422")]
			public virtual RepoItemInfo UnitNumInfo
			{
				get
				{
					return _unitnumInfo;
				}
			}

			/// <summary>
			/// The ServiceTypeOption item.
			/// </summary>
			[RepositoryItem("18a51a00-7bf3-46b4-92d6-776b4181f410")]
			public virtual Ranorex.InputTag ServiceTypeOption
			{
				get
				{
					return _servicetypeoptionInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The ServiceTypeOption item info.
			/// </summary>
			[RepositoryItemInfo("18a51a00-7bf3-46b4-92d6-776b4181f410")]
			public virtual RepoItemInfo ServiceTypeOptionInfo
			{
				get
				{
					return _servicetypeoptionInfo;
				}
			}

			/// <summary>
			/// The SubmitBtn item.
			/// </summary>
			[RepositoryItem("85b74e3a-02ec-461b-b365-c88cf0a716e8")]
			public virtual Ranorex.InputTag SubmitBtn
			{
				get
				{
					return _submitbtnInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The SubmitBtn item info.
			/// </summary>
			[RepositoryItemInfo("85b74e3a-02ec-461b-b365-c88cf0a716e8")]
			public virtual RepoItemInfo SubmitBtnInfo
			{
				get
				{
					return _submitbtnInfo;
				}
			}

			/// <summary>
			/// The ServiceTypeDriveBy item.
			/// </summary>
			[RepositoryItem("31fbec24-d1c4-4c9f-9e53-c76a543de788")]
			public virtual Ranorex.InputTag ServiceTypeDriveBy
			{
				get
				{
					return _servicetypedrivebyInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The ServiceTypeDriveBy item info.
			/// </summary>
			[RepositoryItemInfo("31fbec24-d1c4-4c9f-9e53-c76a543de788")]
			public virtual RepoItemInfo ServiceTypeDriveByInfo
			{
				get
				{
					return _servicetypedrivebyInfo;
				}
			}

			/// <summary>
			/// The Purchase item.
			/// </summary>
			[RepositoryItem("f69c1733-71d2-49d3-91a9-3a843293cc63")]
			public virtual Ranorex.InputTag Purchase
			{
				get
				{
					return _purchaseInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The Purchase item info.
			/// </summary>
			[RepositoryItemInfo("f69c1733-71d2-49d3-91a9-3a843293cc63")]
			public virtual RepoItemInfo PurchaseInfo
			{
				get
				{
					return _purchaseInfo;
				}
			}

			/// <summary>
			/// The Refinance item.
			/// </summary>
			[RepositoryItem("7294c637-b0ab-4bbf-946f-de40a2c34a8c")]
			public virtual Ranorex.InputTag Refinance
			{
				get
				{
					return _refinanceInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The Refinance item info.
			/// </summary>
			[RepositoryItemInfo("7294c637-b0ab-4bbf-946f-de40a2c34a8c")]
			public virtual RepoItemInfo RefinanceInfo
			{
				get
				{
					return _refinanceInfo;
				}
			}

			/// <summary>
			/// The Price item.
			/// </summary>
			[RepositoryItem("4da22560-7333-48cd-b5c0-2d5e7ff8205b")]
			public virtual Ranorex.InputTag Price
			{
				get
				{
					return _priceInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The Price item info.
			/// </summary>
			[RepositoryItemInfo("4da22560-7333-48cd-b5c0-2d5e7ff8205b")]
			public virtual RepoItemInfo PriceInfo
			{
				get
				{
					return _priceInfo;
				}
			}

			/// <summary>
			/// The MortgageAmt item.
			/// </summary>
			[RepositoryItem("e1ee5977-9dcb-4cb9-b5a1-81ca3e392d47")]
			public virtual Ranorex.InputTag MortgageAmt
			{
				get
				{
					return _mortgageamtInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The MortgageAmt item info.
			/// </summary>
			[RepositoryItemInfo("e1ee5977-9dcb-4cb9-b5a1-81ca3e392d47")]
			public virtual RepoItemInfo MortgageAmtInfo
			{
				get
				{
					return _mortgageamtInfo;
				}
			}

			/// <summary>
			/// The AppRefNbr item.
			/// </summary>
			[RepositoryItem("5f688764-09d5-48bd-a380-ae3342c47239")]
			public virtual Ranorex.InputTag AppRefNbr
			{
				get
				{
					return _apprefnbrInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The AppRefNbr item info.
			/// </summary>
			[RepositoryItemInfo("5f688764-09d5-48bd-a380-ae3342c47239")]
			public virtual RepoItemInfo AppRefNbrInfo
			{
				get
				{
					return _apprefnbrInfo;
				}
			}

			/// <summary>
			/// The AppBraNbr item.
			/// </summary>
			[RepositoryItem("19a61ca8-49ea-43af-b226-22e814fb6bee")]
			public virtual Ranorex.InputTag AppBraNbr
			{
				get
				{
					return _appbranbrInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The AppBraNbr item info.
			/// </summary>
			[RepositoryItemInfo("19a61ca8-49ea-43af-b226-22e814fb6bee")]
			public virtual RepoItemInfo AppBraNbrInfo
			{
				get
				{
					return _appbranbrInfo;
				}
			}

			/// <summary>
			/// The AppName item.
			/// </summary>
			[RepositoryItem("beac09b5-cae9-4655-bd6c-69edccdc2583")]
			public virtual Ranorex.InputTag AppName
			{
				get
				{
					return _appnameInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The AppName item info.
			/// </summary>
			[RepositoryItemInfo("beac09b5-cae9-4655-bd6c-69edccdc2583")]
			public virtual RepoItemInfo AppNameInfo
			{
				get
				{
					return _appnameInfo;
				}
			}

			/// <summary>
			/// The AppContactName item.
			/// </summary>
			[RepositoryItem("75cfc4f9-d0d8-4b65-b218-0631cf7ddf23")]
			public virtual Ranorex.InputTag AppContactName
			{
				get
				{
					return _appcontactnameInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The AppContactName item info.
			/// </summary>
			[RepositoryItemInfo("75cfc4f9-d0d8-4b65-b218-0631cf7ddf23")]
			public virtual RepoItemInfo AppContactNameInfo
			{
				get
				{
					return _appcontactnameInfo;
				}
			}

			/// <summary>
			/// The Tel1 item.
			/// </summary>
			[RepositoryItem("cf077aa8-4f68-46ec-94ac-214a4d1953e4")]
			public virtual Ranorex.InputTag Tel1
			{
				get
				{
					return _tel1Info.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The Tel1 item info.
			/// </summary>
			[RepositoryItemInfo("cf077aa8-4f68-46ec-94ac-214a4d1953e4")]
			public virtual RepoItemInfo Tel1Info
			{
				get
				{
					return _tel1Info;
				}
			}

			/// <summary>
			/// The Tel2 item.
			/// </summary>
			[RepositoryItem("b9cdd3a9-5b1d-4b06-9236-8f126dd0944b")]
			public virtual Ranorex.InputTag Tel2
			{
				get
				{
					return _tel2Info.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The Tel2 item info.
			/// </summary>
			[RepositoryItemInfo("b9cdd3a9-5b1d-4b06-9236-8f126dd0944b")]
			public virtual RepoItemInfo Tel2Info
			{
				get
				{
					return _tel2Info;
				}
			}

			/// <summary>
			/// The Tel3 item.
			/// </summary>
			[RepositoryItem("21d0436e-6988-445f-b303-ebdd4fe2b9e3")]
			public virtual Ranorex.InputTag Tel3
			{
				get
				{
					return _tel3Info.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The Tel3 item info.
			/// </summary>
			[RepositoryItemInfo("21d0436e-6988-445f-b303-ebdd4fe2b9e3")]
			public virtual RepoItemInfo Tel3Info
			{
				get
				{
					return _tel3Info;
				}
			}

			/// <summary>
			/// The BusTel1 item.
			/// </summary>
			[RepositoryItem("92e518e2-9d5a-4577-bb03-de46cd8ab281")]
			public virtual Ranorex.InputTag BusTel1
			{
				get
				{
					return _bustel1Info.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The BusTel1 item info.
			/// </summary>
			[RepositoryItemInfo("92e518e2-9d5a-4577-bb03-de46cd8ab281")]
			public virtual RepoItemInfo BusTel1Info
			{
				get
				{
					return _bustel1Info;
				}
			}

			/// <summary>
			/// The BusTel2 item.
			/// </summary>
			[RepositoryItem("8f9340f1-f39e-4f65-8192-73454505e972")]
			public virtual Ranorex.InputTag BusTel2
			{
				get
				{
					return _bustel2Info.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The BusTel2 item info.
			/// </summary>
			[RepositoryItemInfo("8f9340f1-f39e-4f65-8192-73454505e972")]
			public virtual RepoItemInfo BusTel2Info
			{
				get
				{
					return _bustel2Info;
				}
			}

			/// <summary>
			/// The BusTel3 item.
			/// </summary>
			[RepositoryItem("9fe59ab4-c3f5-4b28-b567-e53769b71f11")]
			public virtual Ranorex.InputTag BusTel3
			{
				get
				{
					return _bustel3Info.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The BusTel3 item info.
			/// </summary>
			[RepositoryItemInfo("9fe59ab4-c3f5-4b28-b567-e53769b71f11")]
			public virtual RepoItemInfo BusTel3Info
			{
				get
				{
					return _bustel3Info;
				}
			}

			/// <summary>
			/// The BusTelExt item.
			/// </summary>
			[RepositoryItem("d1303777-6ad4-41fc-a5e9-38941c711ed1")]
			public virtual Ranorex.InputTag BusTelExt
			{
				get
				{
					return _bustelextInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The BusTelExt item info.
			/// </summary>
			[RepositoryItemInfo("d1303777-6ad4-41fc-a5e9-38941c711ed1")]
			public virtual RepoItemInfo BusTelExtInfo
			{
				get
				{
					return _bustelextInfo;
				}
			}

			/// <summary>
			/// The SpDirection item.
			/// </summary>
			[RepositoryItem("29afea55-820f-4b8e-902d-f2ef56912360")]
			public virtual Ranorex.TextAreaTag SpDirection
			{
				get
				{
					return _spdirectionInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
				}
			}

			/// <summary>
			/// The SpDirection item info.
			/// </summary>
			[RepositoryItemInfo("29afea55-820f-4b8e-902d-f2ef56912360")]
			public virtual RepoItemInfo SpDirectionInfo
			{
				get
				{
					return _spdirectionInfo;
				}
			}

			/// <summary>
			/// The Invoice item.
			/// </summary>
			[RepositoryItem("a8121a17-e9ac-4b17-a00c-22cc72dd37e5")]
			public virtual Ranorex.InputTag Invoice
			{
				get
				{
					return _invoiceInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The Invoice item info.
			/// </summary>
			[RepositoryItemInfo("a8121a17-e9ac-4b17-a00c-22cc72dd37e5")]
			public virtual RepoItemInfo InvoiceInfo
			{
				get
				{
					return _invoiceInfo;
				}
			}

			/// <summary>
			/// The ApplicantPay item.
			/// </summary>
			[RepositoryItem("a7ab662b-3c00-4e67-8d82-a9106c1b5173")]
			public virtual Ranorex.InputTag ApplicantPay
			{
				get
				{
					return _applicantpayInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The ApplicantPay item info.
			/// </summary>
			[RepositoryItemInfo("a7ab662b-3c00-4e67-8d82-a9106c1b5173")]
			public virtual RepoItemInfo ApplicantPayInfo
			{
				get
				{
					return _applicantpayInfo;
				}
			}

			/// <summary>
			/// The SelectAppraiserSubmitBtn item.
			/// </summary>
			[RepositoryItem("4dcc9332-858d-4496-bc96-0a92327cc3fd")]
			public virtual Ranorex.InputTag SelectAppraiserSubmitBtn
			{
				get
				{
					return _selectappraisersubmitbtnInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The SelectAppraiserSubmitBtn item info.
			/// </summary>
			[RepositoryItemInfo("4dcc9332-858d-4496-bc96-0a92327cc3fd")]
			public virtual RepoItemInfo SelectAppraiserSubmitBtnInfo
			{
				get
				{
					return _selectappraisersubmitbtnInfo;
				}
			}

			/// <summary>
			/// The UploadSupportingDocumentsHere item.
			/// </summary>
			[RepositoryItem("a893ef6a-0f00-4754-9555-5dd906532bc9")]
			public virtual Ranorex.StrongTag UploadSupportingDocumentsHere
			{
				get
				{
					return _uploadsupportingdocumentshereInfo.CreateAdapter<Ranorex.StrongTag>(true);
				}
			}

			/// <summary>
			/// The UploadSupportingDocumentsHere item info.
			/// </summary>
			[RepositoryItemInfo("a893ef6a-0f00-4754-9555-5dd906532bc9")]
			public virtual RepoItemInfo UploadSupportingDocumentsHereInfo
			{
				get
				{
					return _uploadsupportingdocumentshereInfo;
				}
			}

			/// <summary>
			/// The YourRequestHasBeenSubmitted item.
			/// </summary>
			[RepositoryItem("b8cea039-73a9-4cc8-be38-3208a4fa9110")]
			public virtual Ranorex.H1Tag YourRequestHasBeenSubmitted
			{
				get
				{
					return _yourrequesthasbeensubmittedInfo.CreateAdapter<Ranorex.H1Tag>(true);
				}
			}

			/// <summary>
			/// The YourRequestHasBeenSubmitted item info.
			/// </summary>
			[RepositoryItemInfo("b8cea039-73a9-4cc8-be38-3208a4fa9110")]
			public virtual RepoItemInfo YourRequestHasBeenSubmittedInfo
			{
				get
				{
					return _yourrequesthasbeensubmittedInfo;
				}
			}

			/// <summary>
			/// The NasReqNum item.
			/// </summary>
			[RepositoryItem("ee7fbbb8-d254-457d-a441-b1145ac14d35")]
			public virtual Ranorex.InputTag NasReqNum
			{
				get
				{
					return _nasreqnumInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The NasReqNum item info.
			/// </summary>
			[RepositoryItemInfo("ee7fbbb8-d254-457d-a441-b1145ac14d35")]
			public virtual RepoItemInfo NasReqNumInfo
			{
				get
				{
					return _nasreqnumInfo;
				}
			}

			/// <summary>
			/// The ClientRefNum item.
			/// </summary>
			[RepositoryItem("e4fc351b-0311-489f-b449-ecfff5e7e1aa")]
			public virtual Ranorex.InputTag ClientRefNum
			{
				get
				{
					return _clientrefnumInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The ClientRefNum item info.
			/// </summary>
			[RepositoryItemInfo("e4fc351b-0311-489f-b449-ecfff5e7e1aa")]
			public virtual RepoItemInfo ClientRefNumInfo
			{
				get
				{
					return _clientrefnumInfo;
				}
			}

			/// <summary>
			/// The StatusOpt item.
			/// </summary>
			[RepositoryItem("12912f1a-8398-4f3a-b64d-9201282a2532")]
			public virtual Ranorex.SelectTag StatusOpt
			{
				get
				{
					return _statusoptInfo.CreateAdapter<Ranorex.SelectTag>(true);
				}
			}

			/// <summary>
			/// The StatusOpt item info.
			/// </summary>
			[RepositoryItemInfo("12912f1a-8398-4f3a-b64d-9201282a2532")]
			public virtual RepoItemInfo StatusOptInfo
			{
				get
				{
					return _statusoptInfo;
				}
			}

			/// <summary>
			/// The CreateDateFrom item.
			/// </summary>
			[RepositoryItem("72877c97-88e0-41e8-961e-15f41aea6275")]
			public virtual Ranorex.InputTag CreateDateFrom
			{
				get
				{
					return _createdatefromInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The CreateDateFrom item info.
			/// </summary>
			[RepositoryItemInfo("72877c97-88e0-41e8-961e-15f41aea6275")]
			public virtual RepoItemInfo CreateDateFromInfo
			{
				get
				{
					return _createdatefromInfo;
				}
			}

			/// <summary>
			/// The CreateDateTo item.
			/// </summary>
			[RepositoryItem("2bb38741-01c8-474f-9a25-f518bf41e263")]
			public virtual Ranorex.InputTag CreateDateTo
			{
				get
				{
					return _createdatetoInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The CreateDateTo item info.
			/// </summary>
			[RepositoryItemInfo("2bb38741-01c8-474f-9a25-f518bf41e263")]
			public virtual RepoItemInfo CreateDateToInfo
			{
				get
				{
					return _createdatetoInfo;
				}
			}

			/// <summary>
			/// The SearchSubmit item.
			/// </summary>
			[RepositoryItem("f78d9d66-c4f4-404d-b758-d4f284d92763")]
			public virtual Ranorex.InputTag SearchSubmit
			{
				get
				{
					return _searchsubmitInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The SearchSubmit item info.
			/// </summary>
			[RepositoryItemInfo("f78d9d66-c4f4-404d-b758-d4f284d92763")]
			public virtual RepoItemInfo SearchSubmitInfo
			{
				get
				{
					return _searchsubmitInfo;
				}
			}

			/// <summary>
			/// The NasNumTdTag item.
			/// </summary>
			[RepositoryItem("39c54391-0502-4aea-ac8a-9f3f5a519043")]
			public virtual Ranorex.TdTag NasNumTdTag
			{
				get
				{
					return _nasnumtdtagInfo.CreateAdapter<Ranorex.TdTag>(true);
				}
			}

			/// <summary>
			/// The NasNumTdTag item info.
			/// </summary>
			[RepositoryItemInfo("39c54391-0502-4aea-ac8a-9f3f5a519043")]
			public virtual RepoItemInfo NasNumTdTagInfo
			{
				get
				{
					return _nasnumtdtagInfo;
				}
			}

			/// <summary>
			/// The CommentOnRequest item.
			/// </summary>
			[RepositoryItem("77ef77d2-cfe8-4958-9676-7925cdf8bc68")]
			public virtual Ranorex.InputTag CommentOnRequest
			{
				get
				{
					return _commentonrequestInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The CommentOnRequest item info.
			/// </summary>
			[RepositoryItemInfo("77ef77d2-cfe8-4958-9676-7925cdf8bc68")]
			public virtual RepoItemInfo CommentOnRequestInfo
			{
				get
				{
					return _commentonrequestInfo;
				}
			}

			/// <summary>
			/// The SendCommentToAppraiserFromClient item.
			/// </summary>
			[RepositoryItem("8d34924f-d6f1-44dc-a132-7a862ab54e21")]
			public virtual Ranorex.InputTag SendCommentToAppraiserFromClient
			{
				get
				{
					return _sendcommenttoappraiserfromclientInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The SendCommentToAppraiserFromClient item info.
			/// </summary>
			[RepositoryItemInfo("8d34924f-d6f1-44dc-a132-7a862ab54e21")]
			public virtual RepoItemInfo SendCommentToAppraiserFromClientInfo
			{
				get
				{
					return _sendcommenttoappraiserfromclientInfo;
				}
			}

			/// <summary>
			/// The LogClientComment item.
			/// </summary>
			[RepositoryItem("19e0d101-7294-4e4c-8ea7-6e4cd5c08b6e")]
			public virtual Ranorex.InputTag LogClientComment
			{
				get
				{
					return _logclientcommentInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The LogClientComment item info.
			/// </summary>
			[RepositoryItemInfo("19e0d101-7294-4e4c-8ea7-6e4cd5c08b6e")]
			public virtual RepoItemInfo LogClientCommentInfo
			{
				get
				{
					return _logclientcommentInfo;
				}
			}

			/// <summary>
			/// The CommentText item.
			/// </summary>
			[RepositoryItem("25f55063-6aab-4d73-abe5-8255e5814b63")]
			public virtual Ranorex.TextAreaTag CommentText
			{
				get
				{
					return _commenttextInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
				}
			}

			/// <summary>
			/// The CommentText item info.
			/// </summary>
			[RepositoryItemInfo("25f55063-6aab-4d73-abe5-8255e5814b63")]
			public virtual RepoItemInfo CommentTextInfo
			{
				get
				{
					return _commenttextInfo;
				}
			}

			/// <summary>
			/// The SubmitComment item.
			/// </summary>
			[RepositoryItem("606dbd8a-e84c-4969-acd6-f88df46c188a")]
			public virtual Ranorex.InputTag SubmitComment
			{
				get
				{
					return _submitcommentInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The SubmitComment item info.
			/// </summary>
			[RepositoryItemInfo("606dbd8a-e84c-4969-acd6-f88df46c188a")]
			public virtual RepoItemInfo SubmitCommentInfo
			{
				get
				{
					return _submitcommentInfo;
				}
			}

			/// <summary>
			/// The CommentsWereSuccessfullySubmitted item.
			/// </summary>
			[RepositoryItem("4951f5a7-5126-49bf-a181-e8fe591ba254")]
			public virtual Ranorex.DivTag CommentsWereSuccessfullySubmitted
			{
				get
				{
					return _commentsweresuccessfullysubmittedInfo.CreateAdapter<Ranorex.DivTag>(true);
				}
			}

			/// <summary>
			/// The CommentsWereSuccessfullySubmitted item info.
			/// </summary>
			[RepositoryItemInfo("4951f5a7-5126-49bf-a181-e8fe591ba254")]
			public virtual RepoItemInfo CommentsWereSuccessfullySubmittedInfo
			{
				get
				{
					return _commentsweresuccessfullysubmittedInfo;
				}
			}

			/// <summary>
			/// The CommentPosted item.
			/// </summary>
			[RepositoryItem("1bd80c6e-cc05-4fb6-ab9b-17ee4aed5dd3")]
			public virtual Ranorex.TdTag CommentPosted
			{
				get
				{
					return _commentpostedInfo.CreateAdapter<Ranorex.TdTag>(true);
				}
			}

			/// <summary>
			/// The CommentPosted item info.
			/// </summary>
			[RepositoryItemInfo("1bd80c6e-cc05-4fb6-ab9b-17ee4aed5dd3")]
			public virtual RepoItemInfo CommentPostedInfo
			{
				get
				{
					return _commentpostedInfo;
				}
			}

			/// <summary>
			/// The StrongTag1RecordSFound item.
			/// </summary>
			[RepositoryItem("bb6e775b-900e-4c83-b74f-deaba08c4e87")]
			public virtual Ranorex.StrongTag StrongTag1RecordSFound
			{
				get
				{
					return _strongtag1recordsfoundInfo.CreateAdapter<Ranorex.StrongTag>(true);
				}
			}

			/// <summary>
			/// The StrongTag1RecordSFound item info.
			/// </summary>
			[RepositoryItemInfo("bb6e775b-900e-4c83-b74f-deaba08c4e87")]
			public virtual RepoItemInfo StrongTag1RecordSFoundInfo
			{
				get
				{
					return _strongtag1recordsfoundInfo;
				}
			}

			/// <summary>
			/// The PTag item.
			/// </summary>
			[RepositoryItem("8e609488-2adf-4979-8cc8-08ad41bb5cc7")]
			public virtual Ranorex.PTag PTag
			{
				get
				{
					return _ptagInfo.CreateAdapter<Ranorex.PTag>(true);
				}
			}

			/// <summary>
			/// The PTag item info.
			/// </summary>
			[RepositoryItemInfo("8e609488-2adf-4979-8cc8-08ad41bb5cc7")]
			public virtual RepoItemInfo PTagInfo
			{
				get
				{
					return _ptagInfo;
				}
			}

			/// <summary>
			/// The LabelTagNasNum item.
			/// </summary>
			[RepositoryItem("473d2378-3b1c-4b51-8bf0-f64512d2137a")]
			public virtual Ranorex.LabelTag LabelTagNasNum
			{
				get
				{
					return _labeltagnasnumInfo.CreateAdapter<Ranorex.LabelTag>(true);
				}
			}

			/// <summary>
			/// The LabelTagNasNum item info.
			/// </summary>
			[RepositoryItemInfo("473d2378-3b1c-4b51-8bf0-f64512d2137a")]
			public virtual RepoItemInfo LabelTagNasNumInfo
			{
				get
				{
					return _labeltagnasnumInfo;
				}
			}

			/// <summary>
			/// The ViewRequestBtn item.
			/// </summary>
			[RepositoryItem("49948270-ff00-4134-9980-6bbf0b53f848")]
			public virtual Ranorex.InputTag ViewRequestBtn
			{
				get
				{
					return _viewrequestbtnInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The ViewRequestBtn item info.
			/// </summary>
			[RepositoryItemInfo("49948270-ff00-4134-9980-6bbf0b53f848")]
			public virtual RepoItemInfo ViewRequestBtnInfo
			{
				get
				{
					return _viewrequestbtnInfo;
				}
			}

			/// <summary>
			/// The UploadSupportDocuBtn item.
			/// </summary>
			[RepositoryItem("45ebc6e4-64e0-4279-8573-bc0c39366763")]
			public virtual Ranorex.InputTag UploadSupportDocuBtn
			{
				get
				{
					return _uploadsupportdocubtnInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The UploadSupportDocuBtn item info.
			/// </summary>
			[RepositoryItemInfo("45ebc6e4-64e0-4279-8573-bc0c39366763")]
			public virtual RepoItemInfo UploadSupportDocuBtnInfo
			{
				get
				{
					return _uploadsupportdocubtnInfo;
				}
			}

			/// <summary>
			/// The AppraisalHistoryBtn item.
			/// </summary>
			[RepositoryItem("a4416a86-e89a-4ddd-aef8-045b79fc9732")]
			public virtual Ranorex.InputTag AppraisalHistoryBtn
			{
				get
				{
					return _appraisalhistorybtnInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The AppraisalHistoryBtn item info.
			/// </summary>
			[RepositoryItemInfo("a4416a86-e89a-4ddd-aef8-045b79fc9732")]
			public virtual RepoItemInfo AppraisalHistoryBtnInfo
			{
				get
				{
					return _appraisalhistorybtnInfo;
				}
			}

			/// <summary>
			/// The CancelledBtn item.
			/// </summary>
			[RepositoryItem("a7fcb4fe-ede3-4a71-b732-eb76134f0458")]
			public virtual Ranorex.InputTag CancelledBtn
			{
				get
				{
					return _cancelledbtnInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The CancelledBtn item info.
			/// </summary>
			[RepositoryItemInfo("a7fcb4fe-ede3-4a71-b732-eb76134f0458")]
			public virtual RepoItemInfo CancelledBtnInfo
			{
				get
				{
					return _cancelledbtnInfo;
				}
			}

			/// <summary>
			/// The UnderReviewBtn item.
			/// </summary>
			[RepositoryItem("c7446e24-ae90-4759-917e-2e0989e10036")]
			public virtual Ranorex.InputTag UnderReviewBtn
			{
				get
				{
					return _underreviewbtnInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The UnderReviewBtn item info.
			/// </summary>
			[RepositoryItemInfo("c7446e24-ae90-4759-917e-2e0989e10036")]
			public virtual RepoItemInfo UnderReviewBtnInfo
			{
				get
				{
					return _underreviewbtnInfo;
				}
			}

			/// <summary>
			/// The ReviewBtn item.
			/// </summary>
			[RepositoryItem("eca9eb6e-7f49-4153-979d-978c92194755")]
			public virtual Ranorex.InputTag ReviewBtn
			{
				get
				{
					return _reviewbtnInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The ReviewBtn item info.
			/// </summary>
			[RepositoryItemInfo("eca9eb6e-7f49-4153-979d-978c92194755")]
			public virtual RepoItemInfo ReviewBtnInfo
			{
				get
				{
					return _reviewbtnInfo;
				}
			}

			/// <summary>
			/// The AppraisalRequestHistoryReport item.
			/// </summary>
			[RepositoryItem("f917aecb-ebbf-454d-b177-caed778f1d14")]
			public virtual Ranorex.H1Tag AppraisalRequestHistoryReport
			{
				get
				{
					return _appraisalrequesthistoryreportInfo.CreateAdapter<Ranorex.H1Tag>(true);
				}
			}

			/// <summary>
			/// The AppraisalRequestHistoryReport item info.
			/// </summary>
			[RepositoryItemInfo("f917aecb-ebbf-454d-b177-caed778f1d14")]
			public virtual RepoItemInfo AppraisalRequestHistoryReportInfo
			{
				get
				{
					return _appraisalrequesthistoryreportInfo;
				}
			}

			/// <summary>
			/// The AppraisalRequestNumber item.
			/// </summary>
			[RepositoryItem("03a98407-4a29-487e-bbb4-33ed11c68955")]
			public virtual Ranorex.H2Tag AppraisalRequestNumber
			{
				get
				{
					return _appraisalrequestnumberInfo.CreateAdapter<Ranorex.H2Tag>(true);
				}
			}

			/// <summary>
			/// The AppraisalRequestNumber item info.
			/// </summary>
			[RepositoryItemInfo("03a98407-4a29-487e-bbb4-33ed11c68955")]
			public virtual RepoItemInfo AppraisalRequestNumberInfo
			{
				get
				{
					return _appraisalrequestnumberInfo;
				}
			}

			/// <summary>
			/// The RegionType item.
			/// </summary>
			[RepositoryItem("acc764df-6bd0-4105-a72d-ba71b7f2fd82")]
			public virtual Ranorex.H2Tag RegionType
			{
				get
				{
					return _regiontypeInfo.CreateAdapter<Ranorex.H2Tag>(true);
				}
			}

			/// <summary>
			/// The RegionType item info.
			/// </summary>
			[RepositoryItemInfo("acc764df-6bd0-4105-a72d-ba71b7f2fd82")]
			public virtual RepoItemInfo RegionTypeInfo
			{
				get
				{
					return _regiontypeInfo;
				}
			}

			/// <summary>
			/// The TdTagStatus item.
			/// </summary>
			[RepositoryItem("827865c5-71fd-41b6-92e0-21d831e5daba")]
			public virtual Ranorex.TdTag TdTagStatus
			{
				get
				{
					return _tdtagstatusInfo.CreateAdapter<Ranorex.TdTag>(true);
				}
			}

			/// <summary>
			/// The TdTagStatus item info.
			/// </summary>
			[RepositoryItemInfo("827865c5-71fd-41b6-92e0-21d831e5daba")]
			public virtual RepoItemInfo TdTagStatusInfo
			{
				get
				{
					return _tdtagstatusInfo;
				}
			}

			/// <summary>
			/// The TdTagAppPrice item.
			/// </summary>
			[RepositoryItem("3a730fa9-b11c-4395-8634-c770e52eb082")]
			public virtual Ranorex.TdTag TdTagAppPrice
			{
				get
				{
					return _tdtagapppriceInfo.CreateAdapter<Ranorex.TdTag>(true);
				}
			}

			/// <summary>
			/// The TdTagAppPrice item info.
			/// </summary>
			[RepositoryItemInfo("3a730fa9-b11c-4395-8634-c770e52eb082")]
			public virtual RepoItemInfo TdTagAppPriceInfo
			{
				get
				{
					return _tdtagapppriceInfo;
				}
			}

			/// <summary>
			/// The TdTagAppPriceTax item.
			/// </summary>
			[RepositoryItem("5c8faddf-d749-4b0d-b7da-5b5240358733")]
			public virtual Ranorex.TdTag TdTagAppPriceTax
			{
				get
				{
					return _tdtagapppricetaxInfo.CreateAdapter<Ranorex.TdTag>(true);
				}
			}

			/// <summary>
			/// The TdTagAppPriceTax item info.
			/// </summary>
			[RepositoryItemInfo("5c8faddf-d749-4b0d-b7da-5b5240358733")]
			public virtual RepoItemInfo TdTagAppPriceTaxInfo
			{
				get
				{
					return _tdtagapppricetaxInfo;
				}
			}

			/// <summary>
			/// The TdTagTimeStamp item.
			/// </summary>
			[RepositoryItem("3a7f872d-4b02-478f-9622-5f1c7e558b86")]
			public virtual Ranorex.TdTag TdTagTimeStamp
			{
				get
				{
					return _tdtagtimestampInfo.CreateAdapter<Ranorex.TdTag>(true);
				}
			}

			/// <summary>
			/// The TdTagTimeStamp item info.
			/// </summary>
			[RepositoryItemInfo("3a7f872d-4b02-478f-9622-5f1c7e558b86")]
			public virtual RepoItemInfo TdTagTimeStampInfo
			{
				get
				{
					return _tdtagtimestampInfo;
				}
			}

			/// <summary>
			/// The AppraisalServiceInfo item.
			/// </summary>
			[RepositoryItem("8e586b38-3c70-4c3f-84f7-9164d4389d8f")]
			public virtual Ranorex.TdTag AppraisalServiceInfo
			{
				get
				{
					return _appraisalserviceinfoInfo.CreateAdapter<Ranorex.TdTag>(true);
				}
			}

			/// <summary>
			/// The AppraisalServiceInfo item info.
			/// </summary>
			[RepositoryItemInfo("8e586b38-3c70-4c3f-84f7-9164d4389d8f")]
			public virtual RepoItemInfo AppraisalServiceInfoInfo
			{
				get
				{
					return _appraisalserviceinfoInfo;
				}
			}

			/// <summary>
			/// The AddressInfo item.
			/// </summary>
			[RepositoryItem("a7b240dc-0248-4536-b1f1-dd7f78e17e1c")]
			public virtual Ranorex.TdTag AddressInfo
			{
				get
				{
					return _addressinfoInfo.CreateAdapter<Ranorex.TdTag>(true);
				}
			}

			/// <summary>
			/// The AddressInfo item info.
			/// </summary>
			[RepositoryItemInfo("a7b240dc-0248-4536-b1f1-dd7f78e17e1c")]
			public virtual RepoItemInfo AddressInfoInfo
			{
				get
				{
					return _addressinfoInfo;
				}
			}

			/// <summary>
			/// The PostalCodeInfo item.
			/// </summary>
			[RepositoryItem("e02c17cb-2cbf-412f-9a5c-8588a5094e9c")]
			public virtual Ranorex.TdTag PostalCodeInfo
			{
				get
				{
					return _postalcodeinfoInfo.CreateAdapter<Ranorex.TdTag>(true);
				}
			}

			/// <summary>
			/// The PostalCodeInfo item info.
			/// </summary>
			[RepositoryItemInfo("e02c17cb-2cbf-412f-9a5c-8588a5094e9c")]
			public virtual RepoItemInfo PostalCodeInfoInfo
			{
				get
				{
					return _postalcodeinfoInfo;
				}
			}

			/// <summary>
			/// The Priceinformation item.
			/// </summary>
			[RepositoryItem("d5b9980a-647f-4f64-9616-793bd25a36ee")]
			public virtual Ranorex.TdTag Priceinformation
			{
				get
				{
					return _priceinformationInfo.CreateAdapter<Ranorex.TdTag>(true);
				}
			}

			/// <summary>
			/// The Priceinformation item info.
			/// </summary>
			[RepositoryItemInfo("d5b9980a-647f-4f64-9616-793bd25a36ee")]
			public virtual RepoItemInfo PriceinformationInfo
			{
				get
				{
					return _priceinformationInfo;
				}
			}

			/// <summary>
			/// The MortgageInformation item.
			/// </summary>
			[RepositoryItem("efb81b76-b4f4-4fdd-aff1-2a6f6c775b22")]
			public virtual Ranorex.TdTag MortgageInformation
			{
				get
				{
					return _mortgageinformationInfo.CreateAdapter<Ranorex.TdTag>(true);
				}
			}

			/// <summary>
			/// The MortgageInformation item info.
			/// </summary>
			[RepositoryItemInfo("efb81b76-b4f4-4fdd-aff1-2a6f6c775b22")]
			public virtual RepoItemInfo MortgageInformationInfo
			{
				get
				{
					return _mortgageinformationInfo;
				}
			}

			/// <summary>
			/// The ClientRefNbrInfo item.
			/// </summary>
			[RepositoryItem("99df1708-2dcd-4440-9e3c-33b136608077")]
			public virtual Ranorex.TdTag ClientRefNbrInfo
			{
				get
				{
					return _clientrefnbrinfoInfo.CreateAdapter<Ranorex.TdTag>(true);
				}
			}

			/// <summary>
			/// The ClientRefNbrInfo item info.
			/// </summary>
			[RepositoryItemInfo("99df1708-2dcd-4440-9e3c-33b136608077")]
			public virtual RepoItemInfo ClientRefNbrInfoInfo
			{
				get
				{
					return _clientrefnbrinfoInfo;
				}
			}

			/// <summary>
			/// The DateCreatedInfo item.
			/// </summary>
			[RepositoryItem("c0101e01-6b55-4d6a-836c-bcb15f23002a")]
			public virtual Ranorex.TdTag DateCreatedInfo
			{
				get
				{
					return _datecreatedinfoInfo.CreateAdapter<Ranorex.TdTag>(true);
				}
			}

			/// <summary>
			/// The DateCreatedInfo item info.
			/// </summary>
			[RepositoryItemInfo("c0101e01-6b55-4d6a-836c-bcb15f23002a")]
			public virtual RepoItemInfo DateCreatedInfoInfo
			{
				get
				{
					return _datecreatedinfoInfo;
				}
			}

			/// <summary>
			/// The StatusInfo item.
			/// </summary>
			[RepositoryItem("0efac6c3-6591-484e-aa27-d577cbcbbf75")]
			public virtual Ranorex.TdTag StatusInfo
			{
				get
				{
					return _statusinfoInfo.CreateAdapter<Ranorex.TdTag>(true);
				}
			}

			/// <summary>
			/// The StatusInfo item info.
			/// </summary>
			[RepositoryItemInfo("0efac6c3-6591-484e-aa27-d577cbcbbf75")]
			public virtual RepoItemInfo StatusInfoInfo
			{
				get
				{
					return _statusinfoInfo;
				}
			}

			/// <summary>
			/// The NASRequestNumber item.
			/// </summary>
			[RepositoryItem("acf9b1c0-a4b0-4300-a2d4-f74cc1978f21")]
			public virtual Ranorex.DivTag NASRequestNumber
			{
				get
				{
					return _nasrequestnumberInfo.CreateAdapter<Ranorex.DivTag>(true);
				}
			}

			/// <summary>
			/// The NASRequestNumber item info.
			/// </summary>
			[RepositoryItemInfo("acf9b1c0-a4b0-4300-a2d4-f74cc1978f21")]
			public virtual RepoItemInfo NASRequestNumberInfo
			{
				get
				{
					return _nasrequestnumberInfo;
				}
			}

			/// <summary>
			/// The StrongTagViewAppraisalNum item.
			/// </summary>
			[RepositoryItem("ea9f917f-7a3d-4cbf-9868-c09c2bdd5001")]
			public virtual Ranorex.StrongTag StrongTagViewAppraisalNum
			{
				get
				{
					return _strongtagviewappraisalnumInfo.CreateAdapter<Ranorex.StrongTag>(true);
				}
			}

			/// <summary>
			/// The StrongTagViewAppraisalNum item info.
			/// </summary>
			[RepositoryItemInfo("ea9f917f-7a3d-4cbf-9868-c09c2bdd5001")]
			public virtual RepoItemInfo StrongTagViewAppraisalNumInfo
			{
				get
				{
					return _strongtagviewappraisalnumInfo;
				}
			}

			/// <summary>
			/// The StrongTagYourAppraisalHasBeenSen item.
			/// </summary>
			[RepositoryItem("66b8b0b7-383d-4aff-8bdd-e9814020e28a")]
			public virtual Ranorex.StrongTag StrongTagYourAppraisalHasBeenSen
			{
				get
				{
					return _strongtagyourappraisalhasbeensenInfo.CreateAdapter<Ranorex.StrongTag>(true);
				}
			}

			/// <summary>
			/// The StrongTagYourAppraisalHasBeenSen item info.
			/// </summary>
			[RepositoryItemInfo("66b8b0b7-383d-4aff-8bdd-e9814020e28a")]
			public virtual RepoItemInfo StrongTagYourAppraisalHasBeenSenInfo
			{
				get
				{
					return _strongtagyourappraisalhasbeensenInfo;
				}
			}

			/// <summary>
			/// The TableSearchResult item.
			/// </summary>
			[RepositoryItem("f028d486-98b9-4403-8e72-c18457bc3dd7")]
			public virtual Ranorex.Table TableSearchResult
			{
				get
				{
					return _tablesearchresultInfo.CreateAdapter<Ranorex.Table>(true);
				}
			}

			/// <summary>
			/// The TableSearchResult item info.
			/// </summary>
			[RepositoryItemInfo("f028d486-98b9-4403-8e72-c18457bc3dd7")]
			public virtual RepoItemInfo TableSearchResultInfo
			{
				get
				{
					return _tablesearchresultInfo;
				}
			}

			/// <summary>
			/// The LabelTagNasNumberFound item.
			/// </summary>
			[RepositoryItem("f560aa96-34d0-4d20-bdfb-23bb52309771")]
			public virtual Ranorex.LabelTag LabelTagNasNumberFound
			{
				get
				{
					return _labeltagnasnumberfoundInfo.CreateAdapter<Ranorex.LabelTag>(true);
				}
			}

			/// <summary>
			/// The LabelTagNasNumberFound item info.
			/// </summary>
			[RepositoryItemInfo("f560aa96-34d0-4d20-bdfb-23bb52309771")]
			public virtual RepoItemInfo LabelTagNasNumberFoundInfo
			{
				get
				{
					return _labeltagnasnumberfoundInfo;
				}
			}

			/// <summary>
			/// The BrowseFileToUpload item.
			/// </summary>
			[RepositoryItem("498d4528-a437-452d-8038-09b8b6448847")]
			public virtual Ranorex.InputTag BrowseFileToUpload
			{
				get
				{
					return _browsefiletouploadInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The BrowseFileToUpload item info.
			/// </summary>
			[RepositoryItemInfo("498d4528-a437-452d-8038-09b8b6448847")]
			public virtual RepoItemInfo BrowseFileToUploadInfo
			{
				get
				{
					return _browsefiletouploadInfo;
				}
			}

			/// <summary>
			/// The UploadSubmit item.
			/// </summary>
			[RepositoryItem("0f5f6478-c883-417e-8d30-d3ad7f2adb16")]
			public virtual Ranorex.InputTag UploadSubmit
			{
				get
				{
					return _uploadsubmitInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The UploadSubmit item info.
			/// </summary>
			[RepositoryItemInfo("0f5f6478-c883-417e-8d30-d3ad7f2adb16")]
			public virtual RepoItemInfo UploadSubmitInfo
			{
				get
				{
					return _uploadsubmitInfo;
				}
			}

			/// <summary>
			/// The SupportingDocumentPdf item.
			/// </summary>
			[RepositoryItem("20e9fe3b-437c-4c12-ab15-f5dc9baad096")]
			public virtual Ranorex.ATag SupportingDocumentPdf
			{
				get
				{
					return _supportingdocumentpdfInfo.CreateAdapter<Ranorex.ATag>(true);
				}
			}

			/// <summary>
			/// The SupportingDocumentPdf item info.
			/// </summary>
			[RepositoryItemInfo("20e9fe3b-437c-4c12-ab15-f5dc9baad096")]
			public virtual RepoItemInfo SupportingDocumentPdfInfo
			{
				get
				{
					return _supportingdocumentpdfInfo;
				}
			}

			/// <summary>
			/// The SupportingDocumentsHaveBeenUploaded item.
			/// </summary>
			[RepositoryItem("c1d6beb4-eb94-4019-b8c1-20d434d02061")]
			public virtual Ranorex.H2Tag SupportingDocumentsHaveBeenUploaded
			{
				get
				{
					return _supportingdocumentshavebeenuploadedInfo.CreateAdapter<Ranorex.H2Tag>(true);
				}
			}

			/// <summary>
			/// The SupportingDocumentsHaveBeenUploaded item info.
			/// </summary>
			[RepositoryItemInfo("c1d6beb4-eb94-4019-b8c1-20d434d02061")]
			public virtual RepoItemInfo SupportingDocumentsHaveBeenUploadedInfo
			{
				get
				{
					return _supportingdocumentshavebeenuploadedInfo;
				}
			}

			/// <summary>
			/// The ButtonTagYes item.
			/// </summary>
			[RepositoryItem("392551e9-756b-4da6-a9dd-227fbc166e2e")]
			public virtual Ranorex.ButtonTag ButtonTagYes
			{
				get
				{
					return _buttontagyesInfo.CreateAdapter<Ranorex.ButtonTag>(true);
				}
			}

			/// <summary>
			/// The ButtonTagYes item info.
			/// </summary>
			[RepositoryItemInfo("392551e9-756b-4da6-a9dd-227fbc166e2e")]
			public virtual RepoItemInfo ButtonTagYesInfo
			{
				get
				{
					return _buttontagyesInfo;
				}
			}

			/// <summary>
			/// The ButtonTagNo item.
			/// </summary>
			[RepositoryItem("61f21a2f-0bb3-45ac-99f3-04fcae994b1c")]
			public virtual Ranorex.ButtonTag ButtonTagNo
			{
				get
				{
					return _buttontagnoInfo.CreateAdapter<Ranorex.ButtonTag>(true);
				}
			}

			/// <summary>
			/// The ButtonTagNo item info.
			/// </summary>
			[RepositoryItemInfo("61f21a2f-0bb3-45ac-99f3-04fcae994b1c")]
			public virtual RepoItemInfo ButtonTagNoInfo
			{
				get
				{
					return _buttontagnoInfo;
				}
			}

			/// <summary>
			/// The StatusChangedFromNewToCancelledFor item.
			/// </summary>
			[RepositoryItem("17518023-b08b-4b19-ab1e-085fa0a42627")]
			public virtual Ranorex.PTag StatusChangedFromNewToCancelledFor
			{
				get
				{
					return _statuschangedfromnewtocancelledforInfo.CreateAdapter<Ranorex.PTag>(true);
				}
			}

			/// <summary>
			/// The StatusChangedFromNewToCancelledFor item info.
			/// </summary>
			[RepositoryItemInfo("17518023-b08b-4b19-ab1e-085fa0a42627")]
			public virtual RepoItemInfo StatusChangedFromNewToCancelledForInfo
			{
				get
				{
					return _statuschangedfromnewtocancelledforInfo;
				}
			}

			/// <summary>
			/// The StrongTagStatus item.
			/// </summary>
			[RepositoryItem("22dffa42-456b-477d-90df-300b73e97d8b")]
			public virtual Ranorex.StrongTag StrongTagStatus
			{
				get
				{
					return _strongtagstatusInfo.CreateAdapter<Ranorex.StrongTag>(true);
				}
			}

			/// <summary>
			/// The StrongTagStatus item info.
			/// </summary>
			[RepositoryItemInfo("22dffa42-456b-477d-90df-300b73e97d8b")]
			public virtual RepoItemInfo StrongTagStatusInfo
			{
				get
				{
					return _strongtagstatusInfo;
				}
			}

			/// <summary>
			/// The ViewUserReq item.
			/// </summary>
			[RepositoryItem("9341209e-f52c-42cc-aca2-8e1069f18428")]
			public virtual Ranorex.InputTag ViewUserReq
			{
				get
				{
					return _viewuserreqInfo.CreateAdapter<Ranorex.InputTag>(true);
				}
			}

			/// <summary>
			/// The ViewUserReq item info.
			/// </summary>
			[RepositoryItemInfo("9341209e-f52c-42cc-aca2-8e1069f18428")]
			public virtual RepoItemInfo ViewUserReqInfo
			{
				get
				{
					return _viewuserreqInfo;
				}
			}

			/// <summary>
			/// The ActiveReqSample1 item.
			/// </summary>
			[RepositoryItem("24d37fc6-40dc-4a5a-a39a-b6575aa9f5ba")]
			public virtual Ranorex.TableTag ActiveReqSample1
			{
				get
				{
					return _activereqsample1Info.CreateAdapter<Ranorex.TableTag>(true);
				}
			}

			/// <summary>
			/// The ActiveReqSample1 item info.
			/// </summary>
			[RepositoryItemInfo("24d37fc6-40dc-4a5a-a39a-b6575aa9f5ba")]
			public virtual RepoItemInfo ActiveReqSample1Info
			{
				get
				{
					return _activereqsample1Info;
				}
			}
		}

		/// <summary>
		/// The ChooseFileToUploadAppFolder folder.
		/// </summary>
		[RepositoryFolder("e2624051-1e02-48f7-95ea-b0be35d9d8c9")]
		public partial class ChooseFileToUploadAppFolder : RepoGenBaseFolder
		{
			RepoItemInfo _supportdocumentuploadInfo;
			RepoItemInfo _filenameInfo;
			RepoItemInfo _buttonopenInfo;

			/// <summary>
			/// Creates a new ChooseFileToUpload  folder.
			/// </summary>
			public ChooseFileToUploadAppFolder(RepoGenBaseFolder parentFolder) :
					base("ChooseFileToUpload", "/form[@title='Choose File to Upload']", parentFolder, 30000, null, true, "e2624051-1e02-48f7-95ea-b0be35d9d8c9", "")
			{
				_supportdocumentuploadInfo = new RepoItemInfo(this, "SupportDocumentUpload", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']/?/?/listitem[@automationid='2']/text[@automationid='System.ItemNameDisplay' and @uiautomationvaluevalue='TestHousePic']", 30000, null, "431541a9-a5cd-4271-8a6f-8b6877de4507");
				_filenameInfo = new RepoItemInfo(this, "FileName", "?/?/text[@controlid='1148']", 30000, null, "4e967d12-4ae3-4086-bbdd-9acb99b281d1");
				_buttonopenInfo = new RepoItemInfo(this, "ButtonOpen", "button[@text='&Open']", 30000, null, "ea5550e3-efbe-4351-be4c-2a24d4aa9682");
			}

			/// <summary>
			/// The Self item.
			/// </summary>
			[RepositoryItem("e2624051-1e02-48f7-95ea-b0be35d9d8c9")]
			public virtual Ranorex.Form Self
			{
				get
				{
					return _selfInfo.CreateAdapter<Ranorex.Form>(true);
				}
			}

			/// <summary>
			/// The Self item info.
			/// </summary>
			[RepositoryItemInfo("e2624051-1e02-48f7-95ea-b0be35d9d8c9")]
			public virtual RepoItemInfo SelfInfo
			{
				get
				{
					return _selfInfo;
				}
			}

			/// <summary>
			/// The SupportDocumentUpload item.
			/// </summary>
			[RepositoryItem("431541a9-a5cd-4271-8a6f-8b6877de4507")]
			public virtual Ranorex.Text SupportDocumentUpload
			{
				get
				{
					return _supportdocumentuploadInfo.CreateAdapter<Ranorex.Text>(true);
				}
			}

			/// <summary>
			/// The SupportDocumentUpload item info.
			/// </summary>
			[RepositoryItemInfo("431541a9-a5cd-4271-8a6f-8b6877de4507")]
			public virtual RepoItemInfo SupportDocumentUploadInfo
			{
				get
				{
					return _supportdocumentuploadInfo;
				}
			}

			/// <summary>
			/// The FileName item.
			/// </summary>
			[RepositoryItem("4e967d12-4ae3-4086-bbdd-9acb99b281d1")]
			public virtual Ranorex.Text FileName
			{
				get
				{
					return _filenameInfo.CreateAdapter<Ranorex.Text>(true);
				}
			}

			/// <summary>
			/// The FileName item info.
			/// </summary>
			[RepositoryItemInfo("4e967d12-4ae3-4086-bbdd-9acb99b281d1")]
			public virtual RepoItemInfo FileNameInfo
			{
				get
				{
					return _filenameInfo;
				}
			}

			/// <summary>
			/// The ButtonOpen item.
			/// </summary>
			[RepositoryItem("ea5550e3-efbe-4351-be4c-2a24d4aa9682")]
			public virtual Ranorex.Button ButtonOpen
			{
				get
				{
					return _buttonopenInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The ButtonOpen item info.
			/// </summary>
			[RepositoryItemInfo("ea5550e3-efbe-4351-be4c-2a24d4aa9682")]
			public virtual RepoItemInfo ButtonOpenInfo
			{
				get
				{
					return _buttonopenInfo;
				}
			}
		}

		/// <summary>
		/// The NASAppFolder folder.
		/// </summary>
		[RepositoryFolder("92e56e43-c02e-4215-bdef-eaf77ba9a720")]
		public partial class NASAppFolder : RepoGenBaseFolder
		{
			RepoItemInfo _notificationInfo;
			RepoItemInfo _buttonyesInfo;
			RepoItemInfo _notforthissiteInfo;

			/// <summary>
			/// Creates a new NAS  folder.
			/// </summary>
			public NASAppFolder(RepoGenBaseFolder parentFolder) :
					base("NAS", "/form[@title~'^NAS\\ -\\ Nationwide\\ Appraisa']", parentFolder, 30000, null, true, "92e56e43-c02e-4215-bdef-eaf77ba9a720", "")
			{
				_notificationInfo = new RepoItemInfo(this, "Notification", "element[@class='Frame Notification Bar']/?/?/toolbar[@accessiblename='Notification']", 30000, null, "b0311adc-e4c1-49f2-ac41-56da781b9071");
				_buttonyesInfo = new RepoItemInfo(this, "ButtonYes", ".//toolbar[@accessiblename='Notification']/button[@accessiblename='Yes']", 30000, null, "964f69cd-1316-4b20-8a04-b2f6a22b6266");
				_notforthissiteInfo = new RepoItemInfo(this, "NotForThisSite", ".//toolbar[@accessiblename='Notification']/button[@accessiblename='Not for this site']", 30000, null, "39f63d28-bfec-4ad7-b0d8-c952ce624c26");
			}

			/// <summary>
			/// The Self item.
			/// </summary>
			[RepositoryItem("92e56e43-c02e-4215-bdef-eaf77ba9a720")]
			public virtual Ranorex.Form Self
			{
				get
				{
					return _selfInfo.CreateAdapter<Ranorex.Form>(true);
				}
			}

			/// <summary>
			/// The Self item info.
			/// </summary>
			[RepositoryItemInfo("92e56e43-c02e-4215-bdef-eaf77ba9a720")]
			public virtual RepoItemInfo SelfInfo
			{
				get
				{
					return _selfInfo;
				}
			}

			/// <summary>
			/// The Notification item.
			/// </summary>
			[RepositoryItem("b0311adc-e4c1-49f2-ac41-56da781b9071")]
			public virtual Ranorex.ToolBar Notification
			{
				get
				{
					return _notificationInfo.CreateAdapter<Ranorex.ToolBar>(true);
				}
			}

			/// <summary>
			/// The Notification item info.
			/// </summary>
			[RepositoryItemInfo("b0311adc-e4c1-49f2-ac41-56da781b9071")]
			public virtual RepoItemInfo NotificationInfo
			{
				get
				{
					return _notificationInfo;
				}
			}

			/// <summary>
			/// The ButtonYes item.
			/// </summary>
			[RepositoryItem("964f69cd-1316-4b20-8a04-b2f6a22b6266")]
			public virtual Ranorex.Button ButtonYes
			{
				get
				{
					return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The ButtonYes item info.
			/// </summary>
			[RepositoryItemInfo("964f69cd-1316-4b20-8a04-b2f6a22b6266")]
			public virtual RepoItemInfo ButtonYesInfo
			{
				get
				{
					return _buttonyesInfo;
				}
			}

			/// <summary>
			/// The NotForThisSite item.
			/// </summary>
			[RepositoryItem("39f63d28-bfec-4ad7-b0d8-c952ce624c26")]
			public virtual Ranorex.Button NotForThisSite
			{
				get
				{
					return _notforthissiteInfo.CreateAdapter<Ranorex.Button>(true);
				}
			}

			/// <summary>
			/// The NotForThisSite item info.
			/// </summary>
			[RepositoryItemInfo("39f63d28-bfec-4ad7-b0d8-c952ce624c26")]
			public virtual RepoItemInfo NotForThisSiteInfo
			{
				get
				{
					return _notforthissiteInfo;
				}
			}
		}

	}
#pragma warning restore 0436
}
